repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: "{{ cookiecutter.formal_name }}/manifest.yml"
      - id: check-json
      - id: check-xml
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
