name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

defaults:
  run:
    shell: bash # https://github.com/beeware/briefcase/pull/912

jobs:
  verify-apps:
    name: Build apps
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
        # Pyside2 and Pyside6, and PPB configs aren't known to work on Linux Flatpak at this time.
        framework: ["toga"]
        include:
          - # Need to use at least 22.04 to get the bugfix in flatpak for handling spaces in filenames.
            platform: ubuntu-22.04
            briefcase-data-dir: ~/.cache/briefcase
            pip-cache-dir: ~/.cache/pip
            # cache action cannot cache docker images (actions/cache#31)
            # docker-cache-dir: /var/lib/docker
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Cache Briefcase tools
        uses: actions/cache@v3.0.11
        with:
          key: briefcase-${{ matrix.platform }}
          path: |
            ~/.cookiecutters
            ${{ matrix.briefcase-data-dir }}
            ${{ matrix.pip-cache-dir }}
            ${{ matrix.docker-cache-dir }}
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install system dependencies
        run: |
          sudo apt-get install -y flatpak flatpak-builder
      - name: Install packages
        run: pip install briefcase
      - name: Build Flatpak project
        run: |
          cd tests/apps/verify-${{ matrix.framework }}
          briefcase create linux flatpak
          briefcase build linux flatpak
          briefcase package linux flatpak --adhoc-sign
